# Eliza Configuration
actions: []
clients:
  - twitter
  - telegram
settings:
  TELEGRAM_BOT_TOKEN: "7779098677:AAGFQYvqFePQgcP7sHGNDyEmfGz4MYv-udA"
  TWITTER_API_KEY: "5mrcDgYbDR3G7c3uTwqQYjM4I"
  TWITTER_API_KEY_SECRET: "081t8u5dLR5S3TeiqGn0ZuQQDowUkVU66WnSA55qhqMeYG8zXw"
  TWITTER_BEARER_TOKEN: "AAAAAAAAAAAAAAAAAAAAAPQyxAEAAAAApZ390hNN5vewnHgcoezRcbzP13E%3DJXXPacVrspPYqNNvN8qST5VQFQIVppm1uhWJjFSsz7qTT6ARWY"
  TWITTER_ACCESS_TOKEN: "1657608724096356354-hybhS7x9Ko6zOg3iKjSzaVziDnxXb2"
  TWITTER_ACCESS_TOKEN_SECRET: "zM2KpE9ixkMTxO1hT9QJ2c0UlqCcyCNPpxSvFAA55Qaiu"
  TWITTER_CLIENT_ID: "dGMteW9aVVFBcEdQZllneW1pc1o6MTpjaQ"
  TWITTER_APP_ID: "29635316"
  TWITTER_CLIENT_SECRET: "NVCj9C_9Jwz20KQVePwf4mYTZA1aKqwY-HBiJsYrqfh1LQriG4"
  TWITTER_USERNAME: "cheshiregpt"
  TWITTER_EMAIL: "cheshireterminal@gmail.com"
  TWITTER_PASSWORD: "Bbjp732!"
  TWITTER_2FA_SECRET: ""
  TWITTER_COOKIES: ""
